### ISSUE TITLE
exit返回值反了

### ISSUE THREAD

**Issue by lishxlin** [ufec/CampusNet#1]
在young.sh的checkLogin()函数中
return的状态似乎用反了![Screenshot_20220917-001347.jpg](https://user-images.githubusercontent.com/32219659/190684781-62d5f26f-73d6-486f-8e10-5835bb4292c5.jpg)

**Comment by lishxlin** [comment]
这是我给Openwrt写init script时，在luci页面上偶然看到的

**Comment by ufec** [comment]
展示一个例子证实写反了

**Comment by ufec** [comment]
@lishxlin 
展示一个例子证实写反了

**Comment by lishxlin** [comment]
> @lishxlin 展示一个例子证实写反了

---

> 这里的脚本我仅仅修改了username和password

---

### 这是账号密码正确的情况下运行脚本

[![asciicast](https://asciinema.org/a/XilQztJ8xZ7J5FsP2NO0qKMUM.svg)](https://asciinema.org/a/XilQztJ8xZ7J5FsP2NO0qKMUM)

> 可以看到此时登陆成功了，但返回了一个exit 1

---

### 这是账号密码不正确的情况下运行脚本

[![asciicast](https://asciinema.org/a/qdewbg81M7QDbmvngDCVsdVcU.svg)](https://asciinema.org/a/qdewbg81M7QDbmvngDCVsdVcU)

> 可以看到此时登陆失败，但返回了一个exit 0

---

综上，这个小问题可能会对一些编写脚本的人产生困扰.

**Comment by ufec** [comment]
不太了解，一般来说我认为 `1` 代表 `true`， `0` 代表 `fasle`，所以就在认证成功返回`1`，认证失败返回`0`了。可能在一些 `api` 接口中会以 `0` 代表一切正常，个人习惯罢了，如果说会对二开产生困惑，我还是乐意合并这个`PR`的，感谢!

**Comment by ufec** [comment]
不太了解，一般来说我认为 `1` 代表 `true`， `0` 代表 `fasle`，所以就在认证成功返回`1`，认证失败返回`0`了。可能在一些 `api` 接口中会以 `0` 代表一切正常，个人习惯罢了，如果说会对二开产生困惑，我还是乐意合并这个`PR`的，感谢!
